"""
PDF Generator using ReportLab
"""
import os
import re
import io
from datetime import datetime
from flask import current_app

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch, cm
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                     TableStyle, HRFlowable, Image as RLImage,
                                     PageBreak)
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
    from reportlab.graphics.shapes import Drawing
    from reportlab.pdfgen import canvas
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

try:
    import qrcode
    QR_AVAILABLE = True
except ImportError:
    QR_AVAILABLE = False


DARK_BLUE  = colors.HexColor('#0d1b4b')
SKY_BLUE   = colors.HexColor('#1e90ff')
LIGHT_GRAY = colors.HexColor('#f5f7fa')
MID_GRAY   = colors.HexColor('#6c757d')


def _clean_html(html_text: str) -> str:
    """Strip HTML tags for plain text PDF rendering."""
    text = re.sub(r'<br\s*/?>', '\n', html_text, flags=re.IGNORECASE)
    text = re.sub(r'<[^>]+>', '', text)
    text = re.sub(r'&nbsp;', ' ', text)
    text = re.sub(r'&amp;', '&', text)
    text = re.sub(r'&lt;', '<', text)
    text = re.sub(r'&gt;', '>', text)
    return text.strip()


def _parse_html_to_paragraphs(html_text: str, styles) -> list:
    """Parse HTML content into ReportLab Paragraph objects."""
    story = []

    # Split by block-level tags
    blocks = re.split(r'(<h[1-6][^>]*>.*?</h[1-6]>|<p[^>]*>.*?</p>|<ul>.*?</ul>|<ol>.*?</ol>|<hr\s*/?>\s*|<table[^>]*>.*?</table>)',
                      html_text, flags=re.DOTALL | re.IGNORECASE)

    for block in blocks:
        block = block.strip()
        if not block:
            continue

        # Headings
        h_match = re.match(r'<(h[1-6])[^>]*>(.*?)</h[1-6]>', block, re.IGNORECASE | re.DOTALL)
        if h_match:
            level = h_match.group(1).lower()
            text  = _clean_html(h_match.group(2)).strip()
            style_map = {
                'h1': styles['Title'],
                'h2': styles['Heading2'],
                'h3': styles['Heading3'],
                'h4': styles['Heading4'],
                'h5': styles['Normal'],
                'h6': styles['Normal'],
            }
            story.append(Spacer(1, 6))
            story.append(Paragraph(text, style_map.get(level, styles['Heading3'])))
            story.append(Spacer(1, 4))
            continue

        # HR
        if re.match(r'<hr\s*/?>', block, re.IGNORECASE):
            story.append(HRFlowable(width='100%', thickness=1, color=DARK_BLUE))
            story.append(Spacer(1, 6))
            continue

        # Paragraph
        p_match = re.match(r'<p[^>]*>(.*?)</p>', block, re.IGNORECASE | re.DOTALL)
        if p_match:
            text = _clean_html(p_match.group(1)).strip()
            if text:
                story.append(Paragraph(text, styles['BodyText']))
                story.append(Spacer(1, 4))
            continue

        # Plain text
        text = _clean_html(block).strip()
        if text and len(text) > 10:
            story.append(Paragraph(text, styles['BodyText']))
            story.append(Spacer(1, 4))

    return story


class NumberedCanvas(canvas.Canvas):
    """Canvas that adds page numbers, watermark, and footer."""

    def __init__(self, *args, company_name='', **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []
        self.company_name = company_name

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_page_extras(total)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def _draw_page_extras(self, total_pages):
        self.saveState()
        w, h = A4

        # Watermark
        self.setFont('Helvetica', 50)
        self.setFillColorRGB(0.9, 0.9, 0.95, alpha=0.15)
        self.translate(w / 2, h / 2)
        self.rotate(45)
        self.drawCentredString(0, 0, 'LexReg AI')
        self.rotate(-45)
        self.translate(-w / 2, -h / 2)

        # Footer line
        self.setStrokeColor(DARK_BLUE)
        self.setLineWidth(0.5)
        self.line(1.5*cm, 1.8*cm, w - 1.5*cm, 1.8*cm)

        # Footer text
        self.setFont('Helvetica', 8)
        self.setFillColor(MID_GRAY)
        self.drawString(1.5*cm, 1.2*cm, f'Generated by LexReg AI | {self.company_name}')
        self.drawRightString(w - 1.5*cm, 1.2*cm, f'Page {self._pageNumber} of {total_pages}')
        self.drawCentredString(w / 2, 1.2*cm, f'Generated on: {datetime.now().strftime("%d-%m-%Y %H:%M")}')

        self.restoreState()


def generate_pdf(doc_obj, profile) -> str:
    """Generate a professional PDF for the given document."""
    if not REPORTLAB_AVAILABLE:
        raise RuntimeError("ReportLab not installed. Run: pip install reportlab")

    output_dir = current_app.config['GENERATED_DOCS_FOLDER']
    filename   = f"doc_{doc_obj.id}_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
    filepath   = os.path.join(output_dir, filename)

    company_name = profile.company_name if profile else 'LexReg AI'

    def make_canvas(filename, **kwargs):
        return NumberedCanvas(filename, company_name=company_name, **kwargs)

    doc = SimpleDocTemplate(
        filepath,
        pagesize    = A4,
        rightMargin = 1.5*cm,
        leftMargin  = 1.5*cm,
        topMargin   = 2.5*cm,
        bottomMargin = 2.5*cm,
    )

    # Styles
    base_styles = getSampleStyleSheet()
    styles = {
        'Title': ParagraphStyle('DocTitle',
            fontName='Helvetica-Bold', fontSize=16,
            textColor=DARK_BLUE, spaceAfter=6, alignment=TA_CENTER),
        'Heading2': ParagraphStyle('H2',
            fontName='Helvetica-Bold', fontSize=13,
            textColor=DARK_BLUE, spaceAfter=4, spaceBefore=8),
        'Heading3': ParagraphStyle('H3',
            fontName='Helvetica-Bold', fontSize=11,
            textColor=SKY_BLUE, spaceAfter=4, spaceBefore=6),
        'Heading4': ParagraphStyle('H4',
            fontName='Helvetica-Bold', fontSize=10,
            textColor=DARK_BLUE, spaceAfter=2),
        'BodyText': ParagraphStyle('Body',
            fontName='Helvetica', fontSize=10,
            leading=15, textColor=colors.black,
            alignment=TA_JUSTIFY),
        'Normal': base_styles['Normal'],
    }

    story = []

    # ── Header ──────────────────────────────────────────────────────────────
    if profile:
        # Header table: logo + company info
        header_data = [[
            Paragraph(f"""<b>{profile.company_name}</b><br/>
<font size=9>{profile.address}</font><br/>
<font size=9>GST: {profile.gst_number} | PAN: {profile.pan_number}</font><br/>
<font size=9>Email: {profile.email} | Phone: {profile.phone}</font>""",
                ParagraphStyle('CompanyHeader', fontName='Helvetica',
                               fontSize=10, leading=14, textColor=DARK_BLUE)),
        ]]
        header_tbl = Table(header_data, colWidths=[doc.width])
        header_tbl.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), LIGHT_GRAY),
            ('BOX',        (0, 0), (-1, -1), 0.5, DARK_BLUE),
            ('TOPPADDING',    (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
            ('LEFTPADDING',   (0,0), (-1,-1), 12),
        ]))
        story.append(header_tbl)
        story.append(Spacer(1, 12))

    # ── Document Title ───────────────────────────────────────────────────────
    story.append(Paragraph(doc_obj.title.upper(), styles['Title']))
    story.append(HRFlowable(width='100%', thickness=2, color=DARK_BLUE))
    story.append(Spacer(1, 8))

    # ── Document metadata ────────────────────────────────────────────────────
    meta_data = [
        ['Document ID:', f'LEXREG-{doc_obj.id:05d}',
         'Date:', datetime.now().strftime('%d-%m-%Y')],
        ['Status:', doc_obj.status.upper(),
         'Generated:', datetime.now().strftime('%H:%M IST')],
    ]
    meta_tbl = Table(meta_data, colWidths=[3*cm, 6*cm, 3*cm, 6*cm])
    meta_tbl.setStyle(TableStyle([
        ('FONTNAME',   (0,0), (-1,-1), 'Helvetica'),
        ('FONTNAME',   (0,0), (0,-1), 'Helvetica-Bold'),
        ('FONTNAME',   (2,0), (2,-1), 'Helvetica-Bold'),
        ('FONTSIZE',   (0,0), (-1,-1), 9),
        ('TEXTCOLOR',  (0,0), (0,-1), DARK_BLUE),
        ('TEXTCOLOR',  (2,0), (2,-1), DARK_BLUE),
        ('GRID',       (0,0), (-1,-1), 0.25, colors.lightgrey),
        ('BACKGROUND', (0,0), (0,-1), LIGHT_GRAY),
        ('BACKGROUND', (2,0), (2,-1), LIGHT_GRAY),
        ('TOPPADDING',    (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(meta_tbl)
    story.append(Spacer(1, 16))

    # ── Document Content ─────────────────────────────────────────────────────
    content = doc_obj.content or ''
    content_paragraphs = _parse_html_to_paragraphs(content, styles)
    story.extend(content_paragraphs)

    # ── QR Code ──────────────────────────────────────────────────────────────
    if QR_AVAILABLE:
        story.append(Spacer(1, 20))
        story.append(HRFlowable(width='100%', thickness=0.5, color=MID_GRAY))
        qr_data = f"LexReg AI | Doc ID: LEXREG-{doc_obj.id:05d} | {doc_obj.title} | {datetime.now().isoformat()}"
        qr_img  = qrcode.make(qr_data)
        qr_buf  = io.BytesIO()
        qr_img.save(qr_buf, format='PNG')
        qr_buf.seek(0)
        qr_rl = RLImage(qr_buf, width=1.5*cm, height=1.5*cm)
        qr_table = Table([[qr_rl, Paragraph(
            '<font size=8 color="gray">Scan to verify document authenticity<br/>'
            f'Reference: LEXREG-{doc_obj.id:05d}</font>',
            styles['Normal']
        )]], colWidths=[2*cm, doc.width-2*cm])
        story.append(qr_table)

    # ── Build ─────────────────────────────────────────────────────────────────
    doc.build(story, canvasmaker=make_canvas)
    return filepath
