"""
DOCX Export using python-docx
"""
import os
import re
from datetime import datetime
from flask import current_app

try:
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor, Cm
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.style import WD_STYLE_TYPE
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False


def _clean_html(text: str) -> str:
    text = re.sub(r'<br\s*/?>', '\n', text, flags=re.IGNORECASE)
    text = re.sub(r'<[^>]+>', '', text)
    text = re.sub(r'&nbsp;', ' ', text)
    text = re.sub(r'&amp;', '&', text)
    return text.strip()


def _set_heading_color(paragraph, r, g, b):
    run = paragraph.runs
    for r_ in paragraph.runs:
        r_.font.color.rgb = RGBColor(r, g, b)


def generate_docx(doc_obj, profile) -> str:
    """Generate a professional DOCX for the given document."""
    if not DOCX_AVAILABLE:
        raise RuntimeError("python-docx not installed. Run: pip install python-docx")

    output_dir = current_app.config['GENERATED_DOCS_FOLDER']
    filename   = f"doc_{doc_obj.id}_{datetime.now().strftime('%Y%m%d%H%M%S')}.docx"
    filepath   = os.path.join(output_dir, filename)

    word_doc = Document()

    # ── Page margins ──────────────────────────────────────────────────────────
    sections = word_doc.sections
    for section in sections:
        section.top_margin    = Cm(2)
        section.bottom_margin = Cm(2)
        section.left_margin   = Cm(2.5)
        section.right_margin  = Cm(2.5)

    # ── Header ───────────────────────────────────────────────────────────────
    header = word_doc.sections[0].header
    h_para = header.paragraphs[0] if header.paragraphs else header.add_paragraph()
    h_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    h_run  = h_para.add_run('LexReg AI – Automated Legal Document Generation')
    h_run.bold = True
    h_run.font.size = Pt(10)
    h_run.font.color.rgb = RGBColor(13, 27, 75)

    # ── Footer ───────────────────────────────────────────────────────────────
    footer = word_doc.sections[0].footer
    f_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    f_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    f_run  = f_para.add_run(f'Generated by LexReg AI | {datetime.now().strftime("%d-%m-%Y %H:%M")} | Ref: LEXREG-{doc_obj.id:05d}')
    f_run.font.size = Pt(8)
    f_run.font.color.rgb = RGBColor(108, 117, 125)

    # ── Company banner ────────────────────────────────────────────────────────
    if profile:
        banner = word_doc.add_paragraph()
        banner.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r1 = banner.add_run(profile.company_name + '\n')
        r1.bold = True
        r1.font.size = Pt(14)
        r1.font.color.rgb = RGBColor(13, 27, 75)
        r2 = banner.add_run(
            f'{profile.address}\n'
            f'GST: {profile.gst_number}  |  PAN: {profile.pan_number}\n'
            f'Email: {profile.email}  |  Phone: {profile.phone}'
        )
        r2.font.size = Pt(9)

    word_doc.add_paragraph()

    # ── Document title ────────────────────────────────────────────────────────
    title_para = word_doc.add_heading(doc_obj.title.upper(), level=1)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_heading_color(title_para, 13, 27, 75)

    # ── Meta info table ───────────────────────────────────────────────────────
    meta_tbl = word_doc.add_table(rows=2, cols=4)
    meta_tbl.style = 'Table Grid'
    meta_cells = [
        ('Document ID:', f'LEXREG-{doc_obj.id:05d}', 'Date:', datetime.now().strftime('%d-%m-%Y')),
        ('Status:', doc_obj.status.upper(), 'Generated:', datetime.now().strftime('%H:%M IST')),
    ]
    for row_idx, row_data in enumerate(meta_cells):
        row = meta_tbl.rows[row_idx]
        for col_idx, text in enumerate(row_data):
            cell = row.cells[col_idx]
            cell.text = text
            if col_idx % 2 == 0:
                cell.paragraphs[0].runs[0].bold = True

    word_doc.add_paragraph()

    # ── Content ───────────────────────────────────────────────────────────────
    content = doc_obj.content or ''
    blocks  = re.split(r'(<h[1-6][^>]*>.*?</h[1-6]>|<p[^>]*>.*?</p>|<hr\s*/?>\s*|<ul>.*?</ul>)',
                       content, flags=re.DOTALL | re.IGNORECASE)

    for block in blocks:
        block = block.strip()
        if not block:
            continue

        h_match = re.match(r'<(h[1-6])[^>]*>(.*?)</h[1-6]>', block, re.IGNORECASE | re.DOTALL)
        if h_match:
            level_map = {'h1': 1, 'h2': 2, 'h3': 3, 'h4': 4, 'h5': 5, 'h6': 6}
            level = level_map.get(h_match.group(1).lower(), 2)
            text  = _clean_html(h_match.group(2))
            h_para = word_doc.add_heading(text, level=min(level, 4))
            _set_heading_color(h_para, 13, 27, 75)
            continue

        if re.match(r'<hr\s*/?>', block, re.IGNORECASE):
            hr_para = word_doc.add_paragraph('─' * 80)
            hr_para.runs[0].font.color.rgb = RGBColor(200, 200, 200)
            continue

        p_match = re.match(r'<p[^>]*>(.*?)</p>', block, re.IGNORECASE | re.DOTALL)
        if p_match:
            text = _clean_html(p_match.group(1)).strip()
            if text:
                word_doc.add_paragraph(text)
            continue

        text = _clean_html(block).strip()
        if text and len(text) > 10:
            word_doc.add_paragraph(text)

    word_doc.save(filepath)
    return filepath
